### ISSUE TITLE
Any idea why I'm getting Error::Connection?

### ISSUE THREAD

**Issue by glibg10b** [yhirose/cpp-httplib#1225]
```c++
#define CPPHTTPLIB_OPENSSL_SUPPORT
#include "httplib.h"

int main()
{
    httplib::SSLClient bot{ "www.reddit.com/" };
//    bot.set_interface("br0");
    bot.set_basic_auth("<API_KEY>", "<SECRET_KEY>");

    httplib::Headers headers{
        { "user-agent", "api-test by glibg10b" }
    };

    httplib::MultipartFormDataItems items{
        { "grant_type", "password", "", "" },
        { "username",   "glibg10b", "", "" },
        { "password",   "<PASSWORD>", "", "" }
    };

    auto res{ bot.Post("/api/v1/access_token", headers, items) };
    if (res)
        std::cout << res->status << '\n';
    else
        std::cout << to_string(res.error()) << '\n'; // "Connection"
}
```

`getaddrinfo()` returns `false` [here](https://github.com/yhirose/cpp-httplib/blob/020b0db090dc8e197cbedbdc4db7e3120eda5333/httplib.h#L2538), which leads to `sock` being set to `INVALID_SOCKET`. GDB won't let me step into `getaddrinfo()`

Here's a backtrace:

```plaintext
#0  httplib::detail::create_socket<httplib::detail::create_client_socket(char const*, char const*, int, int, bool, std::function<void (int)>, long, long, long, long, long, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, httplib::Error&)::{lambda(int, addrinfo&)#1}>(char const*, char const*, int, int, int, bool, std::function<void (int)>, httplib::detail::create_client_socket(char const*, char const*, int, int, bool, std::function<void (int)>, long, long, long, long, long, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, httplib::Error&)::{lambda(int, addrinfo&)#1}) (host=0x7fffffffdc48 "www.reddit.com/", ip=0x7fffffffd210 "", port=443, address_family=0, 
    socket_flags=0, tcp_nodelay=false, socket_options=..., bind_or_connect=...) at /home/waldo/sources/reddit-api-test/httplib.h:2538
#1  0x0000555555563340 in httplib::detail::create_client_socket(char const*, char const*, int, int, bool, std::function<void (int)>, long, long, long, long, long, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, httplib::Error&) (host=0x7fffffffdc48 "www.reddit.com/", ip=0x7fffffffd210 "", port=443, address_family=0, tcp_nodelay=false, socket_options=..., connection_timeout_sec=300, connection_timeout_usec=0, read_timeout_sec=5, read_timeout_usec=0, 
    write_timeout_sec=5, write_timeout_usec=0, intf="", error=@0x7fffffffd504: httplib::Error::Success) at /home/waldo/sources/reddit-api-test/httplib.h:2678
#2  0x0000555555570a11 in httplib::ClientImpl::create_client_socket (this=0x7fffffffdc30, error=@0x7fffffffd504: httplib::Error::Success) at /home/waldo/sources/reddit-api-test/httplib.h:5821
#3  0x0000555555570ac3 in httplib::ClientImpl::create_and_connect_socket (this=0x7fffffffdc30, socket=..., error=@0x7fffffffd504: httplib::Error::Success) at /home/waldo/sources/reddit-api-test/httplib.h:5830
#4  0x0000555555575faa in httplib::SSLClient::create_and_connect_socket (this=0x7fffffffdc30, socket=..., error=@0x7fffffffd504: httplib::Error::Success) at /home/waldo/sources/reddit-api-test/httplib.h:7454
#5  0x000055555557130f in httplib::ClientImpl::send (this=0x7fffffffdc30, req=..., res=..., error=@0x7fffffffd504: httplib::Error::Success) at /home/waldo/sources/reddit-api-test/httplib.h:5930
#6  0x0000555555573ca3 in httplib::ClientImpl::send_with_content_provider(httplib::Request&, char const*, unsigned long, std::function<bool (unsigned long, unsigned long, httplib::DataSink&)>, std::function<bool (unsigned long, httplib::DataSink&)>, char const*, httplib::Error&) (this=0x7fffffffdc30, req=..., 
    body=0x555555648480 "----cpp-httplib-multipart-data-cWzEG0QGrr6s76my\r\nContent-Disposition: form-data; name=\"grant_type\"\r\n\r\npassword\r\n----cpp-httplib-multipart-data-cWzEG0QGrr6s76my\r\nContent-Disposition: form-data; name=\"u"..., 
    content_length=385, content_provider=..., content_provider_without_length=..., content_type=0x555555644170 "multipart/form-data; boundary=--cpp-httplib-multipart-data-cWzEG0QGrr6s76my", error=@0x7fffffffd504: httplib::Error::Success)
    at /home/waldo/sources/reddit-api-test/httplib.h:6342
#7  0x0000555555573ea2 in httplib::ClientImpl::send_with_content_provider(char const*, char const*, std::multimap<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, httplib::detail::ci, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, char const*, unsigned long, std::function<bool (unsigned long, unsigned long, httplib::DataSink&)>, std::function<bool (unsigned long, httplib::DataSink&)>, char const*) (this=0x7fffffffdc30, method=0x5555555d3a38 "POST", 
    path=0x5555555d42f7 "/api/v1/access_token", headers=std::multimap with 1 element = {...}, 
    body=0x555555648480 "----cpp-httplib-multipart-data-cWzEG0QGrr6s76my\r\nContent-Disposition: form-data; name=\"grant_type\"\r\n\r\npassword\r\n----cpp-httplib-multipart-data-cWzEG0QGrr6s76my\r\nContent-Disposition: form-data; name=\"u"..., 
    content_length=385, content_provider=..., content_provider_without_length=..., content_type=0x555555644170 "multipart/form-data; boundary=--cpp-httplib-multipart-data-cWzEG0QGrr6s76my") at /home/waldo/sources/reddit-api-test/httplib.h:6361
#8  0x0000555555574971 in httplib::ClientImpl::Post (this=0x7fffffffdc30, path=0x5555555d42f7 "/api/v1/access_token", headers=std::multimap with 1 element = {...}, 
    body="----cpp-httplib-multipart-data-cWzEG0QGrr6s76my\r\nContent-Disposition: form-data; name=\"grant_type\"\r\n\r\npassword\r\n----cpp-httplib-multipart-data-cWzEG0QGrr6s76my\r\nContent-Disposition: form-data; name=\"u"..., 
    content_type=0x555555644170 "multipart/form-data; boundary=--cpp-httplib-multipart-data-cWzEG0QGrr6s76my") at /home/waldo/sources/reddit-api-test/httplib.h:6622
#9  0x0000555555574f71 in httplib::ClientImpl::Post (this=0x7fffffffdc30, path=0x5555555d42f7 "/api/v1/access_token", headers=std::multimap with 1 element = {...}, items=std::vector of length 3, capacity 3 = {...}, 
    boundary="--cpp-httplib-multipart-data-cWzEG0QGrr6s76my") at /home/waldo/sources/reddit-api-test/httplib.h:6702
#10 0x0000555555574a32 in httplib::ClientImpl::Post (this=0x7fffffffdc30, path=0x5555555d42f7 "/api/v1/access_token", headers=std::multimap with 1 element = {...}, items=std::vector of length 3, capacity 3 = {...})
    at /home/waldo/sources/reddit-api-test/httplib.h:6671
#11 0x000055555555e53f in main () at main.cpp:20
```

**Comment by yhirose** [comment]
"www.reddit.com/" is an incorrect host name. Should be "www.reddit.com"?

**Comment by glibg10b** [comment]
Yup, thanks
