### ISSUE TITLE
use httplib  v0.12.5 provide a mutipart/formdata  post service, but use java test the api failed.

### ISSUE THREAD

**Issue by Naminwang** [yhirose/cpp-httplib#1577]
jmeter failed info:
java.io.IOException: Error writing to server
	at sun.reflect.GeneratedConstructorAccessor49.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.apache.jmeter.protocol.http.sampler.HTTPJavaImpl.readResponse(HTTPJavaImpl.java:268)
	at org.apache.jmeter.protocol.http.sampler.HTTPJavaImpl.sample(HTTPJavaImpl.java:567)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:66)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1301)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1290)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Error writing to server
	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:699)
	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:711)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1585)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3051)
	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
	at java.net.URLConnection.getContentLength(URLConnection.java:485)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:407)
	at org.apache.jmeter.protocol.http.sampler.HTTPJavaImpl.readResponse(HTTPJavaImpl.java:233)
	... 9 more

**Comment by Naminwang** [comment]
PS: The interface can be invoked successfully when I use postman and python script.

**Comment by Naminwang** [comment]
> jmeter may be opening too many connections; if there are more simultaneous connections than the maximum configured number, the extra connections will be rejected. The default number is 8 or the number of logical CPU threads -1, whichever is higher.
![image](https://github.com/yhirose/cpp-httplib/assets/17474851/dd46dda4-80c6-4d28-b253-9fbe205756d4)
![image](https://github.com/yhirose/cpp-httplib/assets/17474851/6b4c4dde-59b8-45cb-9f4c-8aa621239e5b)

Just 1 thread and call the api 1 time, always gets an error in the image.

**Comment by PixlRainbow** [comment]
how is your httplib server declared and how is `listen` configured? How is the connection URL/domain specified in jmeter?

**Comment by Naminwang** [comment]
httplib server: 
```
httplib::SSLServer svr("resource/sis_standard.pem", "resource/sis_standard.key", nullptr, nullptr, private_key);
svr.Post("/v1/sre/enroll", [&](const httplib::Request &req, httplib::Response &res) {
   std::string file_content;
    if (req.is_multipart_form_data()) {
            file_content= req.get_file_value("AUDIO").content;
     }
}
```

listen:
`svr.listen("127.0.0.1", "8080");`

jmeter config:
![image](https://github.com/yhirose/cpp-httplib/assets/17474851/63d052b2-f830-4aa5-8ac8-412d3f9de9c7)

**Comment by yhirose** [comment]
@Naminwang if it works when you use postman or a python script, I don't think it's a problem of cpp-httplib. Could you try with a different HTTP server with your jmeter?

**Comment by yhirose** [comment]
@Naminwang please let us know when you get more evidence what shows the issue is really caused by cpp-httplib. Thanks!
